export enum Blockchains {
  Stellar = 1,
  Ethereum = 2,
  Polygon = 3,
  Binance = 4,
  Avalanche = 5,
  Harmony = 6,
  Terra = 7,
  Solana = 8,
  Bitcoin = 9,
  Litecoin = 10,
  Algorand = 11,
  Polkadot = 12,
  Cosmos = 13,
}
